//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C3TekClient.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C3TekClient.Lang.MyResource", typeof(MyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在该行下添加 1 USSD 命令.
        /// </summary>
        internal static string add_more_ussd_after {
            get {
                return ResourceManager.GetString("add_more_ussd_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动关闭.
        /// </summary>
        internal static string auto_off {
            get {
                return ResourceManager.GetString("auto_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动开启.
        /// </summary>
        internal static string auto_on {
            get {
                return ResourceManager.GetString("auto_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余：.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忙碌的.
        /// </summary>
        internal static string busy_or_no_carrier {
            get {
                return ResourceManager.GetString("busy_or_no_carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请更新到新版本使用。 热线电话 0917.111.666.
        /// </summary>
        internal static string cannot_check_version {
            get {
                return ResourceManager.GetString("cannot_check_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查Excel文件的内容.
        /// </summary>
        internal static string check_excel_file {
            get {
                return ResourceManager.GetString("check_excel_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择要发送消息的 sim（按住 ctrl 或 shift 可选择多个）.
        /// </summary>
        internal static string choose_sim_dashboard_to_use {
            get {
                return ResourceManager.GetString("choose_sim_dashboard_to_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string comfirm {
            get {
                return ResourceManager.GetString("comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结果将重新设置，您确定要选择吗？.
        /// </summary>
        internal static string comfirm_reset_all_result {
            get {
                return ResourceManager.GetString("comfirm_reset_all_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接的.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 门.
        /// </summary>
        internal static string custom_prefix_port {
            get {
                return ResourceManager.GetString("custom_prefix_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除所有.
        /// </summary>
        internal static string delete_all {
            get {
                return ResourceManager.GetString("delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 断开连接.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入评论内容！.
        /// </summary>
        internal static string empty_feedback {
            get {
                return ResourceManager.GetString("empty_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取文件时出错，请选择其他文件或在其他软件上关闭当前文件.
        /// </summary>
        internal static string error_read_another_soft {
            get {
                return ResourceManager.GetString("error_read_another_soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入成功，有{0}个空白的USSD记录或端口不在选择的端口列表中。.
        /// </summary>
        internal static string import_success {
            get {
                return ResourceManager.GetString("import_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在队列中.
        /// </summary>
        internal static string in_queue {
            get {
                return ResourceManager.GetString("in_queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入你的电话号码.
        /// </summary>
        internal static string input_phone_number {
            get {
                return ResourceManager.GetString("input_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帐号或密码错误.
        /// </summary>
        internal static string invalid_login {
            get {
                return ResourceManager.GetString("invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 买了调制解调器.
        /// </summary>
        internal static string is_bought_modem {
            get {
                return ResourceManager.GetString("is_bought_modem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请购买一个包来使用该工具！.
        /// </summary>
        internal static string login_subscription {
            get {
                return ResourceManager.GetString("login_subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前登录.
        /// </summary>
        internal static string logining {
            get {
                return ResourceManager.GetString("logining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有一个更新版本。 请访问 lamsim.biz 查看更新、下载和安装最新版本。 衷心感谢！ 热线电话 0917.111.666.
        /// </summary>
        internal static string newer_version {
            get {
                return ResourceManager.GetString("newer_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到门.
        /// </summary>
        internal static string no_found_port {
            get {
                return ResourceManager.GetString("no_found_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您需要升级您的计划才能使用此功能.
        /// </summary>
        internal static string no_subscription_permission {
            get {
                return ResourceManager.GetString("no_subscription_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 还没买调制解调器.
        /// </summary>
        internal static string not_bought_modem {
            get {
                return ResourceManager.GetString("not_bought_modem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 门.
        /// </summary>
        internal static string port {
            get {
                return ResourceManager.GetString("port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理.
        /// </summary>
        internal static string processed {
            get {
                return ResourceManager.GetString("processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加工.
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您确定要将它们全部删除吗？.
        /// </summary>
        internal static string question_comfirm_delete_all {
            get {
                return ResourceManager.GetString("question_comfirm_delete_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 节省.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已保存.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接错误.
        /// </summary>
        internal static string sms_error_connection {
            get {
                return ResourceManager.GetString("sms_error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短信发送错误.
        /// </summary>
        internal static string sms_error_send {
            get {
                return ResourceManager.GetString("sms_error_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功，接收状态未知.
        /// </summary>
        internal static string sms_success_no_state {
            get {
                return ResourceManager.GetString("sms_success_no_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感谢您的反馈！\我们对此表示感谢，并尽快回复您！.
        /// </summary>
        internal static string thanks_feedback {
            get {
                return ResourceManager.GetString("thanks_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请稍候系统更新IMEI.
        /// </summary>
        internal static string wait_update_imei {
            get {
                return ResourceManager.GetString("wait_update_imei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请等待调制解调器完成加载数据，由于与硬件设备的交互，文件传输可能需要很长时间。 在使用其他功能之前，请确保文件传输已完成.
        /// </summary>
        internal static string wait_upload_file {
            get {
                return ResourceManager.GetString("wait_upload_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检查您设备的互联网连接或确保您购买了 C3TEK 的 4G 调制解调器.
        /// </summary>
        internal static string warning_consume_condition {
            get {
                return ResourceManager.GetString("warning_consume_condition", resourceCulture);
            }
        }
    }
}
